### ISSUE TITLE
curl - not returning body content

### ISSUE THREAD

**Issue by pixelcrash** [jeremybernstein/shell#1]
I tried to use the shell object on a MAC / Max/Msp 6 and the curl command. It doesn't return the content value. If I use it with "curl url -i" I get the header information, but still no body content. It works fine in the terminal.

**Comment by jeremybernstein** [comment]
Hi @pixelcrash Are you using the latest version of the object [here](https://github.com/jeremybernstein/shell/releases/tag/1.0b2)? I honestly don't know if the latest versions still run in Max 6, though.

For instance, in Max 8, I get:

```
print: HTTP/1.1 301 Moved Permanently
print: Server: nginx/1.10.3 (Ubuntu)
print: Date: Wed, 22 Apr 2020 14:17:28 GMT
print: Content-Type: text/html
print: Content-Length: 194
print: Connection: keep-alive
print: Location: https://cycling74.com/
print: <html>
print: <head><title>301 Moved Permanently</title></head>
print: <body bgcolor=white>
print: <center><h1>301 Moved Permanently</h1></center>
print: <hr><center>nginx/1.10.3 (Ubuntu)</center>
print: </body>
print: </html>

```

**Comment by jeremybernstein** [comment]
closing in absence of follow-up
