### ISSUE TITLE
Print command on windows

### ISSUE THREAD

**Issue by herbsthauch** [jeremybernstein/shell#2]
Hey Jeremy,
thanks for your great work, unfortunately I have some issues.
I am on Win10 with Max8 and I am trying to send a command to print a textfile through a network printer.
The command to do this through the windows command line is: 

> `print /d:\\herbsthauch\brother c:\users\herbsthauch\documents\test.txt`

unfortunately I cannot get this to work with a message to the shell object. I tried different variations of slashes, backslashes, for example:

> `"print /d:\\herbsthauch\\brother c:\\users\\herbsthauch\\documents\\test.txt"`

this just outputs "device couldn't be initialized"

I would gladly appreciate any help with this!
Cheers 
Jan

**Comment by jeremybernstein** [comment]
Did you try `"print /d:\\\\herbsthauch\\brother c:\\users\\herbsthauch\\documents\\test.txt"`. I'm not set up for printing on my Windows environments, so it might take a minute to test this.

**Comment by herbsthauch** [comment]
Well that was a quick fix, it worked, thank you for the help!
I tried it with three backslashes, didn't think about using four.
