### ISSUE TITLE
object won't load on Big Sur 

### ISSUE THREAD

**Issue by jjburred** [jeremybernstein/shell#5]
I'm trying to load v1.0b3 on Max 8.2.0 under Big Sur (M1 Mac). The external won't load "due to system security policy". I tried removing the quarantine attribute via
`xattr -d com.apple.quarantine [path/to/extern.mxo]`
as suggested here https://cycling74.com/articles/using-unsigned-max-externals-on-mac-os-10-15-catalina , without luck. 
Any hints? thanks in advance

**Comment by jeremybernstein** [comment]
Try ad hoc code signing the extern? `codesign --force --deep -s - shell.mxo`. I'll be sure to do this for the next release.

**Comment by jjburred** [comment]
that did the trick, thanks!
