### ISSUE TITLE
release zip as max package

### ISSUE THREAD

**Issue by maybites** [jeremybernstein/shell#6]
Hi Jeremy

I wonder if you could update your release as a fully fledged package, with icon and json file.

cheers

martin

**Comment by jeremybernstein** [comment]
sure

**Comment by maybites** [comment]
much appreciated. my dependency check for packages is not working when there is no package-info.json inside the package...

**Comment by jeremybernstein** [comment]
https://github.com/jeremybernstein/shell/releases/tag/1.0b4

**Comment by maybites** [comment]
works like a charm. Thank you.

**Comment by maybites** [comment]
one little error: you entered the wrong version number inside the json file.

Version 8.2.0  is now displayed inside the package manager.. but it should be 1.0.0, right?

**Comment by jeremybernstein** [comment]
thanks, zip archive updated
