### ISSUE TITLE
max 8 crashes with py and py_repl

### ISSUE THREAD

**Issue by francescopapaleo** [jeremybernstein/shell#9]
Hi 
Thanks for the amazing work. It's really something that is missing for Max users!

I have been playing around with the externals, either from package or compiled, on my 2015 MacBook with 10.15 (used ```make homebrew-ext```).
 
While sending messages to the py object Max has crashed:

```Max(45323,0x1119fbdc0) malloc: *** error for object 0x12695e1d0: pointer being freed was not allocated```

I attach here the full log. It happened a few times. 
If that can help I also post a screenshot of the patch opened.
Once again, thank you for all that!

[max_crash_log.txt](https://github.com/jeremybernstein/shell/files/10833806/max_crash_log.txt)
<img width="972" alt="Screenshot 2023-02-26 at 14 42 06" src="https://user-images.githubusercontent.com/98514696/221414055-8cba062f-787a-4464-958c-9b68e984a82b.png">

**Comment by jeremybernstein** [comment]
Hi, this doesn't appear to have anything to do with the `shell` object, maybe post this report on the Max forum?

**Comment by francescopapaleo** [comment]
Really sorry! I posted here by mistake
I don't think I can delete it here, but if you can go for it
